opt_in_rules:
  - implicit_return
  - empty_string
  - convenience_type
  - toggle_bool
  - modifier_order
  - implicitly_unwrapped_optional
  - weak_delegate
  - missing_docs
  - closure_end_indentation
  - fatal_error_message
  - indentation_width
  - joined_default_parameter
  - multiline_parameters_brackets
  - private_outlet
  - private_subject
  - unused_declaration
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call

included:
  - LivefrontChallenge

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane

comment_spacing:
  severity: error

convenience_type:
  severity: error

vertical_whitespace:
  severity: error

indentation_width:
  severity: error

fatal_error_message:
  severity: error

closure_end_indentation:
  severity: error

vertical_parameter_alignment_on_call:
  severity: error

unused_import:
  severity: error

unneeded_parentheses_in_closure_argument:
  severity: error

unused_declaration:
  severity: error

multiline_parameters_brackets:
  severity: error

joined_default_parameter:
  severity: error

trailing_whitespace:
  severity: error

implicit_return:
  severity: error

colon:
  severity: error

unused_closure_parameter:
  severity: error

missing_docs: error

force_unwrapping:
  severity: error

line_length: 2000
file_length: 40000
type_body_length: 800

function_parameter_count: 20
function_body_length: 600

identifier_name:
  allowed_symbols: "_"
